// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package masonTTpackage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AxxxxxClient is the client API for Axxxxx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AxxxxxClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type axxxxxClient struct {
	cc grpc.ClientConnInterface
}

func NewAxxxxxClient(cc grpc.ClientConnInterface) AxxxxxClient {
	return &axxxxxClient{cc}
}

func (c *axxxxxClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/masonTTschema.masonTTpackage.Axxxxx/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AxxxxxServer is the server API for Axxxxx service.
// All implementations must embed UnimplementedAxxxxxServer
// for forward compatibility
type AxxxxxServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAxxxxxServer()
}

// UnimplementedAxxxxxServer must be embedded to have forward compatible implementations.
type UnimplementedAxxxxxServer struct {
}

func (UnimplementedAxxxxxServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAxxxxxServer) mustEmbedUnimplementedAxxxxxServer() {}

// UnsafeAxxxxxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AxxxxxServer will
// result in compilation errors.
type UnsafeAxxxxxServer interface {
	mustEmbedUnimplementedAxxxxxServer()
}

func RegisterAxxxxxServer(s grpc.ServiceRegistrar, srv AxxxxxServer) {
	s.RegisterService(&Axxxxx_ServiceDesc, srv)
}

func _Axxxxx_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxxxxxServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/masonTTschema.masonTTpackage.Axxxxx/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxxxxxServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Axxxxx_ServiceDesc is the grpc.ServiceDesc for Axxxxx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Axxxxx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masonTTschema.masonTTpackage.Axxxxx",
	HandlerType: (*AxxxxxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Axxxxx_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Axxxxx.proto",
}
